# Generated by Django 4.2.6 on 2024-02-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_url',
            field=models.CharField(default='https://firebasestorage.googleapis.com/v0/b/social-2f752.appspot.com/o/profile_pics%2Fdefault_profile_pic.png?alt=media&token=78bff1b3-b8c5-497d-a4d5-831f8c5e8360', max_length=600),
        ),
    ]
